### ISSUE TITLE
ModuleNotFoundError: No module named 'gray_swan' when importing AsyncGraySwan

### ISSUE THREAD

**Issue by xl631212** [jplhughes/bon-jailbreaking#14]
I encountered a ModuleNotFoundError when trying to run the code containing the following import statement:

python
Copy code
from gray_swan import AsyncGraySwan
The error message is as follows:

vbnet
Copy code
ModuleNotFoundError: No module named 'gray_swan'

**Comment by danvctr** [comment]
I'm also getting the same error, here is the full traceback

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/notebooks/jailbreak-experiments/bon-jailbreaking/bon/attacks/run_text_bon.py", line 17, in <module>
    from bon.apis.inference.api import InferenceAPI
  File "/notebooks/jailbreak-experiments/bon-jailbreaking/bon/apis/__init__.py", line 1, in <module>
    from .inference.api import InferenceAPI
  File "/notebooks/jailbreak-experiments/bon-jailbreaking/bon/apis/inference/api.py", line 37, in <module>
    from .gray_swan import GRAYSWAN_MODELS, GraySwanChatModel
  File "/notebooks/jailbreak-experiments/bon-jailbreaking/bon/apis/inference/gray_swan.py", line 7, in <module>
    from gray_swan import AsyncGraySwan
ModuleNotFoundError: No module named 'gray_swan'
```

**Comment by jplhughes** [comment]
Thanks for raising the issue! I've bumped all the packages in requirements.txt and added missing ones (https://github.com/jplhughes/bon-jailbreaking/pull/15). Hopefully that works for you guys on `main` now
